test(e2e): Add sketch export functionality test (#3553)
* add test_export_sketch e2e test

* fix plaso path

* fix paths

* fix unused variable

* fix UnboundLocalError

* fix AttributeError: 'Series' object has no attribute 'iteritems'

* fix AttributeError: 'Series' object has no attribute 'iteritems'

* fix lint