Changes to `tsctl.py` (#3365)
* remove revoked as arg in tsctl

* fix another small bug     task_id = task["id"]
TypeError: string indices must be integers

* add worker name to the celery table

---------

Co-authored-by: Janosch <99879757+jkppr@users.noreply.github.com>